import { useState, useRef, useEffect } from "react";
import { Card, CardBody, CardHeader, CardFooter } from "@heroui/card";
import { Button } from "@heroui/button";
import { Input } from "@heroui/input";
import { ScrollShadow } from "@heroui/scroll-shadow";
import { Avatar } from "@heroui/avatar";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { sendChatMessage, getChatHistory, clearChatHistory, getChatSessions, createChatSession, deleteChatSession } from "@/lib/api";
import { Chip } from "@heroui/chip";
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { DeleteIcon } from "./icons";

import { Tooltip } from "@heroui/tooltip";

export default function ChatWidget({ projectId, className, compact = false }: { projectId: string, className?: string, compact?: boolean }) {
  const [activeSessionId, setActiveSessionId] = useState<string | null>(null);
  const [message, setMessage] = useState("");
  const [view, setView] = useState<'list' | 'chat'>('list');
  const scrollRef = useRef<HTMLDivElement>(null);
  const queryClient = useQueryClient();

  const { data: sessions } = useQuery({
    queryKey: ['chat-sessions', projectId],
    queryFn: () => getChatSessions(projectId)
  });

  const { data: history, isLoading } = useQuery({
    queryKey: ['chat', projectId, activeSessionId],
    queryFn: () => getChatHistory(projectId, activeSessionId || undefined),
    enabled: true
  });
  
  // Auto-select most recent session if none selected
  useEffect(() => {
      if (!compact && sessions && sessions.length > 0 && !activeSessionId) {
          setActiveSessionId(sessions[0].id);
      }
      if (compact) {
          if (activeSessionId) setView('chat');
          else setView('list');
      }
  }, [sessions, compact, activeSessionId]);

  const chatMutation = useMutation({
    mutationFn: (msg: string) => sendChatMessage({ project_id: projectId, message: msg, session_id: activeSessionId || undefined }),
    onSuccess: (data) => {
      setMessage("");
      queryClient.invalidateQueries({ queryKey: ['chat', projectId, activeSessionId] });
      // Refresh sessions to get new title if autogenerated or new session created
      queryClient.invalidateQueries({ queryKey: ['chat-sessions', projectId] });
      if (!activeSessionId && data.session_id) {
          setActiveSessionId(data.session_id);
          setView('chat');
      }
    },
    onError: (error: any) => {
        alert("Nepodařilo se odeslat zprávu: " + (error.response?.data?.detail || error.message));
    }
  });

  const createSessionMutation = useMutation({
      mutationFn: () => createChatSession(projectId),
      onSuccess: (newSession) => {
          queryClient.invalidateQueries({ queryKey: ['chat-sessions', projectId] });
          setActiveSessionId(newSession.id);
          setView('chat');
      }
  });

  const deleteSessionMutation = useMutation({
      mutationFn: (id: number) => deleteChatSession(String(id)),
      onSuccess: () => {
          queryClient.invalidateQueries({ queryKey: ['chat-sessions', projectId] });
          if (activeSessionId) setActiveSessionId(null);
      }
  });

  // Scroll to bottom when history changes
  useEffect(() => {
    if (scrollRef.current) {
        setTimeout(() => {
            if (scrollRef.current) {
                scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
            }
        }, 100);
    }
  }, [history, activeSessionId, chatMutation.isPending, view]);

  const handleSend = () => {
    if (!message.trim()) return;
    // If no session exists, create one implicitly or explicitly? 
    // Backend handles implicit if we pass session_id=null but we want to clear UI.
    // If we want "New Chat" logic, we should probably create session first or let backend handle it.
    // My backend logic: if session_id provided, use it. If not, separate history? No, I didn't enforce session_id.
    // But I changed backend to `session = crud.get_chat_session`.
    
    // For better UX: If no active session, create one locally first? 
    // Or just send with null and let backend create? 
    // Currently backend create_chat_history takes session_id. If null, it's null.
    // But I want a named session.
    // Let's create a session if none selected OR if explicitly "New Chat".
    if (!activeSessionId && sessions?.length === 0) {
         createSessionMutation.mutateAsync().then((res) => {
             setActiveSessionId(res.id);
             chatMutation.mutate(message); // This might fail if using closure scope variable? No, mutation fn uses updated logic? No.
             // Better: modify chatMutation to accept variables directly
             // Actually I'll just rely on the user creating a chat or being in one.
             // If NO session is selected (e.g. empty state), we should force create one or start one.
         });
    } else {
         chatMutation.mutate(message);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      handleSend();
    }
  };

  const BotIcon = () => (
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M12 2C6.48 2 2 6.48 2 12C2 17.52 6.48 22 12 22C17.52 22 22 17.52 22 12C22 6.48 17.52 2 12 2ZM12 6C13.66 6 15 7.34 15 9C15 10.66 13.66 12 12 12C10.34 12 9 10.66 9 9C9 7.34 10.34 6 12 6ZM12 18C9.33 18 7 16.67 7 15C7 14.38 8.07 13.86 9.85 13.56C10.53 13.79 11.25 13.9 12 13.9C12.75 13.9 13.47 13.79 14.15 13.56C15.93 13.86 17 14.38 17 15C17 16.67 14.67 18 12 18Z" fill="currentColor"/>
    </svg>
  );

  const SendIcon = () => (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M2.01 21L23 12L2.01 3L2 10L17 12L2 14L2.01 21Z" fill="currentColor"/>
    </svg>
  );

  const BackIcon = () => (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M15.41 7.41L14 6L8 12L14 18L15.41 16.59L10.83 12L15.41 7.41Z" fill="currentColor"/>
      </svg>
  );

  const showList = !compact || view === 'list';
  const showChat = !compact || view === 'chat';

  return (
    <div className={`flex h-full w-full bg-transparent ${className}`}>
        {/* Sidebar */}
        {showList && (
            <div className={`${compact ? 'w-full' : 'w-64'} border-r border-default-200 flex flex-col bg-transparent flex-shrink-0`}>
                <div className="p-4 border-b border-default-200 flex justify-between items-center h-14">
                    <span className="font-bold text-small">Historie konverzací</span>
                    <Tooltip content="Nový chat">
                        <Button size="sm" isIconOnly variant="flat" onPress={() => createSessionMutation.mutate()} color="primary">
                            <span className="text-lg">+</span>
                        </Button>
                    </Tooltip>
                </div>
                <ScrollShadow className="flex-grow p-2 space-y-1">
                    {sessions?.map((session: any) => (
                        <div 
                            key={session.id} 
                            className={`p-3 mx-2 my-1 rounded-medium text-sm cursor-pointer flex justify-between group items-center transition-colors ${activeSessionId === session.id ? 'bg-primary text-primary-foreground font-medium' : 'hover:bg-default-100 text-default-600'}`}
                            onClick={() => {
                                setActiveSessionId(session.id);
                                if (compact) setView('chat');
                            }}
                        >
                            <span className="truncate">{session.name}</span>
                            <Button 
                                isIconOnly 
                                size="sm" 
                                variant="light" 
                                className={`opacity-0 group-hover:opacity-100 min-w-[20px] w-5 h-5 ${activeSessionId === session.id ? 'text-primary-foreground/70 hover:text-primary-foreground' : 'text-danger'}`}
                                onPress={(e) => {
                                    (e as unknown as React.MouseEvent).stopPropagation?.();
                                    deleteSessionMutation.mutate(session.id);
                                }}
                            >
                                <span className="text-tiny">✕</span>
                            </Button>
                        </div>
                    ))}
                    {sessions?.length === 0 && (
                        <div className="text-tiny text-default-400 p-2 text-center">Zatím žádné chaty.</div>
                    )}
                </ScrollShadow>
            </div>
        )}

        {/* Chat Area */}
        {showChat && (
            <div className="flex-1 flex flex-col min-w-0">
                 <div className="p-4 border-b border-divider flex items-center justify-between h-14 bg-default-50/80 backdrop-blur-md sticky top-0 z-10">
                     <div className="flex items-center gap-2 overflow-hidden">
                        {compact && (
                            <Tooltip content="Zpět na historii">
                                <Button isIconOnly variant="light" size="sm" onPress={() => setView('list')} className="-ml-2">
                                    <BackIcon />
                                </Button>
                            </Tooltip>
                        )}
                        <BotIcon />
                        <span className="font-semibold truncate">{activeSessionId ? sessions?.find((s:any) => s.id === activeSessionId)?.name : 'Vyberte chat'}</span>
                     </div>
                     {/* <span className="text-tiny text-default-400">Gemini 2.0 Flash</span> */}
                 </div>

                 <ScrollShadow className="flex-grow p-4 space-y-4" ref={scrollRef}>
                {(!activeSessionId && (!sessions || sessions.length === 0)) ? (
                    <div className="h-full flex flex-col items-center justify-center text-default-400 gap-4">
                        <BotIcon />
                        <p>Vytvořte nový chat pro začátek.</p>
                        <Button color="primary" onPress={() => createSessionMutation.mutate()}>Začít nový chat</Button>
                    </div>
                ) : (
                    <>
                        {history?.map((msg: any) => (
                             <div key={msg.id} className={`flex gap-3 ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                                {msg.role !== 'user' && (
                                    <Avatar icon={<BotIcon />} classNames={{ base: "bg-default-200 text-default-600 flex-shrink-0" }} size="sm" />
                                )}
                                <div className={`max-w-[85%] px-4 py-3 shadow-none ${
                                    msg.role === 'user' 
                                    ? 'bg-primary text-primary-foreground rounded-2xl rounded-br-none' 
                                    : 'bg-default-100 text-foreground rounded-2xl rounded-bl-none'
                                }`}>
                                     <div className={`text-sm leading-relaxed prose prose-sm max-w-none ${msg.role === 'user' ? 'prose-invert' : 'dark:prose-invert prose-stone'}`}>
                                        <ReactMarkdown remarkPlugins={[remarkGfm]}>{msg.content}</ReactMarkdown>
                                    </div>
                                </div>
                             </div>
                        ))}
                    </>
                )}
                {chatMutation.isPending && (
                     <div className="flex gap-3 justify-start items-end fade-in">
                       <Avatar icon={<BotIcon />} classNames={{ base: "bg-default-200 text-default-500 flex-shrink-0" }} size="sm" />
                       <div className="bg-default-100 p-4 rounded-2xl rounded-bl-none w-16 flex items-center justify-center">
                         <div className="flex gap-1">
                            <div className="w-1.5 h-1.5 bg-default-400 rounded-full animate-bounce [animation-delay:-0.3s]"></div>
                            <div className="w-1.5 h-1.5 bg-default-400 rounded-full animate-bounce [animation-delay:-0.15s]"></div>
                            <div className="w-1.5 h-1.5 bg-default-400 rounded-full animate-bounce"></div>
                         </div>
                       </div>
                     </div>
                )}
             </ScrollShadow>

             <div className="p-4 border-t border-divider bg-transparent">
                <Input
                    placeholder="Napište zprávu..."
                    value={message}
                    onValueChange={setMessage}
                    onKeyDown={handleKeyDown}
                    radius="lg"
                    variant="bordered"
                    isDisabled={!activeSessionId}
                    endContent={
                        <Button isIconOnly size="sm" color="primary" variant="solid" onPress={handleSend} isLoading={chatMutation.isPending} radius="full">
                            <SendIcon />
                        </Button>
                    }
                />
             </div>
        </div>
        )}
    </div>
  );
}
